name: IAS Scan
on:
  push:
    branches: [ master ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - id: my-scan
        uses: sstephenson-r7/insightappsec-scan-github-actions@v1.3.1
        with:
          region: us
          api-key: "fakeAPIKey"
          scan-config-id: "fakeScanID"
          scan-timeout-mins: 1
          vuln-query: "vulnerability.severity = 'HIGH'"
      - name: Upload findings
        if: always()
        run: echo "${{ steps.my-scan.outputs.scan-findings }}"
  deploy:
    runs-on: ubuntu-latest
    needs: [scan]
    steps:
      - name: Deploy artifact
        run: echo "Deploying..."